// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijrthzkqsszbxagyzzwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqcnRoemtxc3N6YnhhZ3l6endqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk3OTU0MzYsImV4cCI6MjA2NTM3MTQzNn0.bMrjvY2umGDq5hdtxn9Xy8t0II-aOMWyQPQjVDH10n4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);